default:
  is_secure: true

registerlogon:
  is_secure: false

registerlogoff:
  is_secure: false

list:
  credentials: [ admin ]

viewbyuser:
  credentials: [ admin ]

viewbyworkstation:
  credentials: [ admin ]
