.TH SCHOOLMESH_POSIXACCOUNT_CHANGEUSERNAME 8 "December 2011" "Schoolmesh User Manuals"
.SH NAME
.PP
schoolmesh_posixaccount_changeusername - Change username for the
posix account of a user
.SH SYNOPSIS
.PP
schoolmesh_posixaccount_changeusername \f[I]new_username\f[]
\f[I]old_username\f[]
.SH DESCRIPTION
.PP
Use this script to change the username of a user.
.SH WARNINGS
.PP
If the user has also external accounts, theese won't be affected.
Internal accounts, like samba, that depend on the existence of
posix one, will be deleted, but \f[I]not recreated\f[].
.SH EXAMPLES
.PP
schoolmesh_posixaccount_changeusername johnn john
.SH BUGS
.PP
Probably many.
.SH SEE ALSO
.PP
The SchoolMesh project is described at
<http://schoolmesh.mattiussilab.net/>.
.SH AUTHORS
Loris Tissino (loris.tissino\@mattiussilab.net).

