.TH SCHOOLMESH_WORKSTATION_DISABLEINTERNETACCESS 8 "December 2011" "Schoolmesh User Manuals"
.SH NAME
.PP
schoolmesh_workstation_disableinternetaccess - Disable Internet
access for a workstation
.SH SYNOPSIS
.PP
schoolmesh_workstation_disableinternetaccess \f[I]ipaddress\f[]
\f[I]user\f[]
.SH DESCRIPTION
.PP
This script disables Internet access for a workstation.
.SH EXAMPLES
.PP
schoolmesh_workstation_disableinternetaccess 192.168.1.3 john
.SH BUGS
.PP
Probably many.
.SH SEE ALSO
.PP
The SchoolMesh project is described at
<http://schoolmesh.mattiussilab.net/>.
.SH AUTHORS
Loris Tissino (loris.tissino\@mattiussilab.net).

