.TH SCHOOLMESH_POSIXACCOUNT_CHANGEGROUP 8 "December 2011" "Schoolmesh User Manuals"
.SH NAME
.PP
schoolmesh_posixaccount_changegroup - Change the primary group of a
user
.SH SYNOPSIS
.PP
schoolmesh_posixaccount_changegroup \f[I]username\f[]
\f[I]group\f[]
.SH DESCRIPTION
.PP
Use this script to change the primary group of a user.
.SH EXAMPLES
.PP
schoolmesh_posixaccount_changegroup john students
.SH BUGS
.PP
Probably many.
.SH SEE ALSO
.PP
The SchoolMesh project is described at
<http://www.schoolmesh.mattiussilab.net/>.
.SH AUTHORS
Loris Tissino (loris.tissino\@gmail.com).

