all:
  school:
    name:           ITC Mattiussi
    town:           Pordenone
    website:        'http://www.itcmattiussi.it'

  mail:
    webmaster:      loris.tissino@mattiussilab.net
    
  config:
    current_year:   2008  # only the first of the two years of a scholastic/academic year
    posix_homedir: /home/testhome 
    posix_basefolder: Mattiussi  # this folder contains symbolic links and other stuff; should be present in each homedir
    teachers_default_posix_group: docenti
    students_default_posix_group: allievi
    class_teachersteam_prefix: cdc  # for the new team of teachers automatically created, and the name will be prefixed with this
    class_teachersteam_name: Consiglio di classe
    googleapps_domain: mattiussilab.net
    googleapps_url: http://webmail.mattiussilab.net

  ldap:
    host: localhost
    domain: dc=tissino,dc=it


  sf_guard_plugin:
    check_password_callable: [ldap, checkLdapPassword]

  prelogin:
    token: sekretToken  

  opendocument:
    template_directory: /var/schoolmesh/web/oo  