all:
  school:
    name:           ITC Mattiussi
    town:           Pordenone
    website:        'http://www.itcmattiussi.it'

  mail:
    webmaster:      loris.tissino@mattiussilab.net
    
  config:
    current_year:   2008  # only the first of the two years of a scholastic/academic year
    culture: it
    base_url: 'https://localhost/schoolmesh'
    posix_homedir: /home/testhome 
    posix_basefolder: Mattiussi  # this folder contains symbolic links and other stuff; should be present in each homedir
    teachers_default_posix_group: docenti
    default_teams_role: member
    students_default_posix_group: allievi
    class_teachersteam_prefix: cdc  # for the new team of teachers automatically created, and the name will be prefixed with this
    class_teachersteam_name: Consiglio di classe
    googleapps_domain: mattiussilab.net
    googleapps_url: http://webmail.mattiussilab.net
    accounts: [ posix, login, samba, googleapps ]


  sf_guard_plugin:
    check_password_callable: [Authentication, testOnly]

# to validate the user, the function testOnly() in the Authentication class will be used
# comment this line to use standard authentication (against the db)

# or choose one of the following functions:
# testOnly: all users are authenticated whatever password (but null) they provide
# checkLdapPassword: users are authenticated against a LDAP server, specified in the lines below
# checkSambaPassword: users are authenticated against a Samba server (probably working also against a Windows authentication server)

  authentication:
    ldap:
      host: localhost
      domain: dc=example,dc=com
    samba:
      share: //example/homes
      address: 192.168.1.1

  system:
    commands_view: true
    commands_apply: false

  prelogin:
    token: sekretToken  

  opendocument:
    template_directory: /var/schoolmesh/web/oo  