schoolmaster:
  url: schoolmaster
  param: { module: schoolmaster, action: index } 

office:
  url: office
  param: { module: office, action: index } 

submit:
  url: plansandreports/:id/submit.html
  param: { module: plansandreports, action: wpsubmit } 
  options:
    module:              plansandreports
    prefix_path:        plansandreports

addtool:
  url: plansandreports/addtool/:id/tool/:tool
  param: { module: plansandreports, action: addtool } 
  options:
    module:              plansandreports
    prefix_path:        plansandreports

removetool:
  url: plansandreports/removetool/:id/tool/:tool
  param: { module: plansandreports, action: removetool } 
  options:
    module:              plansandreports
    prefix_path:        plansandreports

appointment:
  class: sfPropelRouteCollection
  options:
    model:               Appointment
    module:              schoolmaster_plansandreports
    prefix_path:         schoolmaster_plansandreports
    column:              id
    with_wildcard_routes: true

lanlogin:
  url:   /lanlogin/:username/:workstation/:ip
  param: { module: lanlog, action: create } 
  requirements:
    ip: \d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}

lanlogout:
  url:   /lanlogout/:username/:workstation/:ip
  param: { module: lanlog, action: update }  
  requirements:
    ip: \d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}

profile:
  url:  /profile
  param: {module: profile, action: index }


sf_guard_user_profile:
  class: sfPropelRouteCollection
  options:
    model:               sfGuardUserProfile
    module:              sf_guard_user_profile
    prefix_path:         sf_guard_user_profile
    column:              user_id
    with_wildcard_routes: true

subnet:
  class: sfPropelRouteCollection
  options:
    model:               Subnet
    module:              subnet
    prefix_path:         subnet
    column:              id
    with_wildcard_routes: true

role:
  class: sfPropelRouteCollection
  options:
    model:               Role
    module:              role
    prefix_path:         role
    column:              id
    with_wildcard_routes: true

workstation:
  class: sfPropelRouteCollection
  options:
    model:               Workstation
    module:              workstation
    prefix_path:         workstation
    column:              id
    with_wildcard_routes: true

plansandreports:
  class: sfPropelRouteCollection
  options:
    model:               Appointment
    module:              plansandreports
    prefix_path:        plansandreports
    column:              id
    with_wildcard_routes: true



service:
  class: sfPropelRouteCollection
  options:
    model:               Service
    module:              service
    prefix_path:         service
    column:              id
    with_wildcard_routes: true


whosonline:
  url:   /whosonline/:sf_format
  param: { module: lanlog, action: index, sf_format: html }
  requirements:
    sf_format: (?:html|atom|txt)

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }
 
sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }
 
sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }



# default rules

homepage:
  url:   /
  param: { module: content, action: index }

default_symfony:
  url:   /symfony/:action/*
  param: { module: default }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
  
