default:
  credentials: [[ teams ]]
new:
  credentials: [[ teams ]]
show:
  credentials: [[ ]]
edit:
  credentials: [[ teams ]]
  
delete:
  credentials: [[ admin ]]  
  
viewlogs:
  credentials: [[ admin ]]  

