generator:
  class: sfPropelGenerator
  param:
    model_class:           Enrolment
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          enrolment
    with_propel_route:     1

    config:
      actions: ~
      fields:  ~
      list:
        display: [ first_name, last_name, schoolclass, year ]
        title: Enrolments\' management
      filter:
        display: [ user_id, schoolclass_id, year_id]
      form:    ~
      edit:    ~
      new:     ~
