.TH SCHOOLMESH 8 "October 2009" "Schoolmesh utilities User Manuals"
.SH NAME
.PP
schoolmesh - command line utilities to be used with SchoolMesh web
application
.SH UTILITY LIST
.PP
schoolmesh_application_createtables -
\f[I]Create empty tables for the database\f[]
.PP
schoolmesh_application_dumptables -
\f[I]Backup data from the database in SQL format\f[]
.PP
schoolmesh_application_importtables -
\f[I]Import data from a backup sql file\f[]
.PP
schoolmesh_application_setstate -
\f[I]Enable/disable the application\f[]
.PP
schoolmesh_application_update -
\f[I]Update the application with the newest SVN release\f[]
.PP
schoolmesh_application_update~ -
\f[I]Update the application with the newest SVN release\f[]
.PP
schoolmesh_loginaccount_changeshell -
\f[I]Change the shell for the login account of a user\f[]
.PP
schoolmesh_loginaccount_getinfo -
\f[I]Get info about the login account of a user\f[]
.PP
schoolmesh_loginaccount_setpassword -
\f[I]Change the login password for a user\f[]
.PP
schoolmesh_loginaccounts_getshells -
\f[I]Get a list of available shells on the system\f[]
.PP
schoolmesh_posixaccount_changefullname -
\f[I]Change full name for a posix account of a user\f[]
.PP
schoolmesh_posixaccount_changegroup -
\f[I]Change the primary group of a user\f[]
.PP
schoolmesh_posixaccount_changeusername -
\f[I]Change username for the posix account of a user\f[]
.PP
schoolmesh_posixaccount_create -
\f[I]Create a posix account for a user\f[]
.PP
schoolmesh_posixaccount_createbasefolder -
\f[I]Create the basefolder for a user\f[]
.PP
schoolmesh_posixaccount_createhomedir -
\f[I]Create the home directory for a user\f[]
.PP
schoolmesh_posixaccount_getinfo -
\f[I]Get info about the posix account of a user\f[]
.PP
schoolmesh_posixaccount_lockuser - \f[I]Lock a user\f[]
.PP
schoolmesh_posixaccount_quotausercheck -
\f[I]Check if the quota of a user was exceeded\f[]
.PP
schoolmesh_posixaccount_repairbasefolder -
\f[I]Repair the basefolder of a user\f[]
.PP
schoolmesh_posixaccount_repairhomedir -
\f[I]Repair the basefolder of a user\f[]
.PP
schoolmesh_posixaccount_setquota - \f[I]Set the quota of a user\f[]
.PP
schoolmesh_posixaccount_unlockuser - \f[I]Unlock a user\f[]
.PP
schoolmesh_posixaccounts_list -
\f[I]Get a list of posix users belonging to a specified group\f[]
.PP
schoolmesh_sambaaccount_create -
\f[I]Create a samba account for a user\f[]
.PP
schoolmesh_sambaaccount_delete -
\f[I]Delete a samba account for a user\f[]
.PP
schoolmesh_sambaaccount_getinfo -
\f[I]Get info about the samba (SMB/CIFS) account of a user\f[]
.SH DESCRIPTION
.PP
These utilities are really only basic wrapper scripts to be used
together with SchoolMesh\. The idea is to provide flexibility\. For
instance, instead of calling directly \f[B]useradd\f[], we call
\f[B]schoolmesh_posixaccount_create\f[]\. This way, if one day we
need to change the behaviour needed to add a system user (for
instance, using \f[I]ldap\f[], or contacting a different server),
we just need to change the wrapper scripts\.
.PP
Each utility should have its own man page (work in progress)\.
.SH BUGS
.PP
Probably many\.
.SH SEE ALSO
.PP
The SchoolMesh project is described at
<http://schoolmesh.mattiussilab.net/>\.
.SH AUTHOR
Loris Tissino
