.TH SCHOOLMESH_POSIXACCOUNT_QUOTAUSERCHECK 8 "December 2009" "Schoolmesh User Manuals"
.SH NAME
.PP
schoolmesh_posixaccount_quotausercheck - Check if the quota of a
user was exceeded
.SH SYNOPSIS
.PP
schoolmesh_posixaccount_quotausercheck \f[I]username\f[]
.SH DESCRIPTION
.PP
Use this script to check if a user has used more space than what is
assumed to\. (This could be the result when you copy files of a
user using administrative privileges)\.
.SH EXAMPLES
.PP
\f[CR]
      schoolmesh_posixaccount_quotausercheck\ john
\f[]
.SH BUGS
.PP
Probably many\.
.SH SEE ALSO
.PP
The SchoolMesh project is described at
<http://schoolmesh.mattiussilab.net/>\.
.SH AUTHOR
Loris Tissino (loris.tissino@mattiussilab.net)
