.TH SCHOOLMESH_SAMBAACCOUNT_DELETE 8 "July 2010" "Schoolmesh User Manuals"
.SH NAME
.PP
schoolmesh_sambaaccount_delete - Delete a samba account for a user
.SH SYNOPSIS
.PP
schoolmesh_sambaaccount_delete \f[I]username\f[]
.SH DESCRIPTION
.PP
Use this script to delete a samba account.
.SH EXAMPLES
.PP
\f[CR]
      schoolmesh_sambaaccount_delete\ john
\f[]
.SH BUGS
.PP
Probably many.
.SH SEE ALSO
.PP
The SchoolMesh project is described at
<http://schoolmesh.mattiussilab.net/>.
.SH AUTHORS
Loris Tissino (loris.tissino\@mattiussilab.net).

