.TH SCHOOLMESH_WORKSTATIONS_GETJOBS 8 "September 2011" "Schoolmesh User Manuals"
.SH NAME
.PP
schoolmesh_workstations_getjobs - Get the list of jobs scheduled
for all the workstations
.SH SYNOPSIS
.PP
schoolmesh_workstations_getjobs go
.SH DESCRIPTION
.PP
This script outputs a list of events, separated by commas,
scheduled for the workstations.
The jobs are in time order.
.SH EXAMPLES
.PP
\f[CR]
      schoolmesh_workstations_getjobs\ go
\f[]
.SH BUGS
.PP
Probably many.
.SH SEE ALSO
.PP
The SchoolMesh project is described at
<http://schoolmesh.mattiussilab.net/>.
.SH AUTHORS
Loris Tissino (loris.tissino\@mattiussilab.net).

