.TH SCHOOLMESH_POSIXACCOUNT_UNLOCKUSER 8 "December 2011" "Schoolmesh User Manuals"
.SH NAME
.PP
schoolmesh_posixaccount_unlockuser - Unlock a user
.SH SYNOPSIS
.PP
schoolmesh_posixaccount_unlockuser \f[I]username\f[]
.SH DESCRIPTION
.PP
Use this script to unlock a user.
.SH EXAMPLES
.PP
schoolmesh_posixaccount_unlockuser john
.SH BUGS
.PP
Probably many.
.SH SEE ALSO
.PP
The SchoolMesh project is described at
<http://schoolmesh.mattiussilab.net/>.
.SH AUTHORS
Loris Tissino (loris.tissino\@mattiussilab.net).

