.TH SCHOOLMESH_APPLICATION_IMPORTTABLES 8 "October 2009" "Schoolmesh User Manuals"
.SH NAME
.PP
schoolmesh_application_importtables - Import data from a backup sql
file
.SH SYNOPSIS
.PP
schoolmesh_application_importtables \f[I]database\f[]
\f[I]inputfile\f[]
.SH DESCRIPTION
.PP
Use this script to import data into the database\. The input file
must be in SQL format\. The output of
\f[I]schoolmesh_application_dumptables(8)\f[] should be adequate\.
.SH WARNINGS
.PP
The database should have the tables, but empty\. It\[aq]s possible
to re-create the tables with
\f[I]schoolmesh_application_createtables(8)\f[]\.
.SH EXAMPLES
.PP
\f[CR]
      schoolmesh_application_importtables\ schoolmesh\ myfile\.sql\ \ 
      schoolmesh_application_importtables\ schoolmesh_prod\ myfile\.sql
\f[]
.SH BUGS
.PP
Probably many\.
.SH SEE ALSO
.PP
The SchoolMesh project is described at
<http://schoolmesh.mattiussilab.net/>\.
.SH AUTHOR
Loris Tissino (loris.tissino@mattiussilab.net)
