.TH SCHOOLMESH_LOGINACCOUNT_GETSHELLS 8 "October 2009" "Schoolmesh User Manuals"
.SH NAME
.PP
schoolmesh_loginaccount_getshells - Get a list of available shells
on the system
.SH SYNOPSIS
.PP
schoolmesh_loginaccount_getshells
.SH DESCRIPTION
.PP
This script generates a list of pairs \f[I]key=value\f[] with the
shells available on the system\.
.SH EXAMPLES
.PP
\f[CR]
      schoolmesh_loginaccount_getshells\ 
\f[]
.SH BUGS
.PP
Probably many\.
.SH SEE ALSO
.PP
The SchoolMesh project is described at
<http://schoolmesh.mattiussilab.net/>\.
.SH AUTHOR
Loris Tissino (loris.tissino@mattiussilab.net)
