.TH SCHOOLMESH_SAMBAACCOUNT_UNLOCK 8 "December 2011" "Schoolmesh User Manuals"
.SH NAME
.PP
schoolmesh_sambaaccount_unlock - Unlock the samba (SMB/CIFS)
account of a user
.SH SYNOPSIS
.PP
schoolmesh_sambaaccount_unlock \f[I]username\f[]
.SH DESCRIPTION
.PP
This script unlocks a samba (SMB/CIFS) account.
.SH EXAMPLES
.PP
schoolmesh_sambaaccount_unlock john
.SH BUGS
.PP
Probably many.
.SH SEE ALSO
.PP
The SchoolMesh project is described at
<http://www.schoolmesh.mattiussilab.net/>.
.SH AUTHORS
Loris Tissino (loris.tissino\@gmail.com).

