.TH SCHOOLMESH_LOGINACCOUNT_CHANGESHELL 8 "July 2010" "Schoolmesh User Manuals"
.SH NAME
.PP
schoolmesh_loginaccount_changeshell - Change the shell for the
login account of a user
.SH SYNOPSIS
.PP
schoolmesh_loginaccount_changeshell \f[I]username\f[]
\f[I]shell\f[]
.SH DESCRIPTION
.PP
Use this script to change the shell of a user.
The shell must be one of those defined in /etc/shells.
.SH EXAMPLES
.PP
\f[CR]
      schoolmesh_loginaccount_changeshell\ john\ /bin/bash
\f[]
.SH BUGS
.PP
Probably many.
.SH SEE ALSO
.PP
The SchoolMesh project is described at
<http://schoolmesh.mattiussilab.net/>.
.SH AUTHORS
Loris Tissino (loris.tissino\@mattiussilab.net).

