.TH SCHOOLMESH_APPLICATION_DUMPTABLES 8 "December 2011" "Schoolmesh User Manuals"
.SH NAME
.PP
schoolmesh_application_dumptables - Backup data from the database
in gzipped SQL format
.SH SYNOPSIS
.PP
schoolmesh_application_dumptables environment outfile
.SH DESCRIPTION
.PP
This script makes a backup of the data of SchoolMesh database, in
the form of a SQL plaintext gzipped file, with foreign key checks
disabled.
The output can be used with
\f[I]schoolmesh_application_importtables(8)\f[].
.SH EXAMPLES
.PP
schoolmesh_application_dumptables prod /var/backups/myfile.sql.gz
.SH BUGS
.PP
Probably many.
.SH SEE ALSO
.PP
The SchoolMesh project is described at
<http://schoolmesh.mattiussilab.net/>.
.SH AUTHORS
Loris Tissino (loris.tissino\@mattiussilab.net).

