.TH SCHOOLMESH_WORKSTATIONS_GETINTERNETENABLED 8 "September 2011" "Schoolmesh User Manuals"
.SH NAME
.PP
schoolmesh_workstations_getinternetenabled - Get the list of
workstations for which Internet access is enabled
.SH SYNOPSIS
.PP
schoolmesh_workstations_getinternetenabled go
.SH DESCRIPTION
.PP
This script outputs a list of IP addresses of workstations for
which Internet access is enabled.
It assumes that the firewall machine uses a special chain and a
special command for rules that must be matched.
The names of the chain and of the comment are in
\f[B]schoolmesh.rc\f[] file.
.SH EXAMPLES
.PP
\f[CR]
      schoolmesh_workstations_getinternetenabled\ 
\f[]
.SH BUGS
.PP
Probably many.
.SH SEE ALSO
.PP
The SchoolMesh project is described at
<http://schoolmesh.mattiussilab.net/>.
.SH AUTHORS
Loris Tissino (loris.tissino\@mattiussilab.net).

