.TH SCHOOLMESH_TASK_EXECUTE 8 "January 2010" "Schoolmesh User Manuals"
.SH NAME
.PP
schoolmesh_task_execute - Executes a symfony SchoolMesh task
.SH SYNOPSIS
.PP
schoolmesh_task_execute \f[I]task\f[] \f[I]parameters\f[]
.SH DESCRIPTION
.PP
This is a wrapper to execute symfony tasks without the need to
change directory or specify or environment \.
.SH EXAMPLES
.PP
\f[CR]
      schoolmesh_task_execute\ extract-info\ appointments\ --teacher\ john\.doe
\f[]
.SH BUGS
.PP
Probably many\.
.SH SEE ALSO
.PP
The SchoolMesh project is described at
<http://schoolmesh.mattiussilab.net/>\.
.SH AUTHOR
Loris Tissino (loris.tissino@mattiussilab.net)
