.TH SCHOOLMESH_SAMBAACCOUNT_CREATE 8 "July 2010" "Schoolmesh User Manuals"
.SH NAME
.PP
schoolmesh_sambaaccount_create - Create a samba account for a user
.SH SYNOPSIS
.PP
schoolmesh_sambaaccount_create \f[I]username\f[] \f[I]fullname\f[]
\f[I]password\f[]
.SH DESCRIPTION
.PP
Use this script to create a posix account.
Some checks are done before the creation.
.SH EXAMPLES
.PP
\f[CR]
      schoolmesh_sambaaccount_create\ john\ \[aq]John\ Doe\[aq]\ ck33LmrdH_45
\f[]
.SH TO DO
.PP
\f[CR]
      Passwords\ should\ not\ be\ passed\ on\ the\ command\ line.\ This\ must\ be\ modified,
\f[]
.PP
probably by passing a file name containing the password.
.SH BUGS
.PP
Probably many.
.SH SEE ALSO
.PP
The SchoolMesh project is described at
<http://schoolmesh.mattiussilab.net/>.
.SH AUTHORS
Loris Tissino (loris.tissino\@mattiussilab.net).

