.TH SCHOOLMESH_SAMBAACCOUNTS_LOG 8 "December 2011" "Schoolmesh User Manuals"
.SH NAME
.PP
schoolmesh_sambaaccounts_log - Ask for registration of logon or
logoff of a user in schoolmesh db
.SH SYNOPSIS
.PP
schoolmesh_sambaaccounts_log [logon|logoff] \f[I]username\f[]
\f[I]machinename\f[] \f[I]ip\f[]
.SH DESCRIPTION
.PP
This script is used from samba to ask for the registration of
logons and logoffs of users from the local network.
Edit your smb.conf adding these lines in [homes] section:
.PP
\f[CR]
      [homes]
      \ ...
      \ preexec\ =\ schoolmesh_sambaaccounts_log\ logon\ %U\ %M\ %m
      \ postexec\ =\ schoolmesh_sambaaccounts_log\ logon\ %U\ %M\ %m
\f[]
.SH EXAMPLES
.PP
schoolmesh_sambaaccounts_log logon john.doe pc13labinf3
192.168.3.13 schoolmesh_sambaaccounts_log logoff john.doe
pc13labinf3 192.168.3.13
.SH BUGS
.PP
Probably many.
.SH SEE ALSO
.PP
The SchoolMesh project is described at
<http://www.schoolmesh.mattiussilab.net/>.
.SH AUTHORS
Loris Tissino (loris.tissino\@gmail.com).

