.TH SCHOOLMESH_SAMBAACCOUNT_GETINFO 8 "July 2010" "Schoolmesh User Manuals"
.SH NAME
.PP
schoolmesh_sambaaccount_getinfo - Get info about the samba
(SMB/CIFS) account of a user
.SH SYNOPSIS
.PP
schoolmesh_sambaaccount_getinfo \f[I]username\f[]
.SH DESCRIPTION
.PP
This script generates a list of pairs \f[I]key=value\f[] about a
samba (SMB/CIFS) account.
If the user is not found, returns \f[I]found=0\f[].
.SH EXAMPLES
.PP
\f[CR]
      schoolmesh_sambaaccount_getinfo\ john
\f[]
.SH BUGS
.PP
Probably many.
.SH SEE ALSO
.PP
The SchoolMesh project is described at
<http://schoolmesh.mattiussilab.net/>.
.SH AUTHORS
Loris Tissino (loris.tissino\@mattiussilab.net).

