.TH SCHOOLMESH_POSIXACCOUNT_GETINFO 8 "December 2009" "Schoolmesh User Manuals"
.SH NAME
.PP
schoolmesh_posixaccount_getinfo - Get info about the posix account
of a user
.SH SYNOPSIS
.PP
schoolmesh_posixaccount_getinfo \f[I]username\f[]
.SH DESCRIPTION
.PP
This script generates a list of pairs \f[I]key=value\f[] about a
posix account\. If the user is not found, returns
\f[I]found=0\f[]\.
.SH EXAMPLES
.PP
\f[CR]
      schoolmesh_posixaccount_getinfo\ john
\f[]
.SH BUGS
.PP
Probably many\.
.SH SEE ALSO
.PP
The SchoolMesh project is described at
<http://schoolmesh.mattiussilab.net/>\.
.SH AUTHOR
Loris Tissino (loris.tissino@mattiussilab.net)
