.TH SCHOOLMESH_SAMBAACCOUNT_UNLOCK 8 "September 2011" "Schoolmesh User Manuals"
.SH NAME
.PP
schoolmesh_sambaaccount_unlock - Unlock the samba (SMB/CIFS)
account of a user
.SH SYNOPSIS
.PP
schoolmesh_sambaaccount_unlock \f[I]username\f[]
.SH DESCRIPTION
.PP
This script unlocks a samba (SMB/CIFS) account.
.SH EXAMPLES
.PP
\f[CR]
      schoolmesh_sambaaccount_unlock\ john
\f[]
.SH BUGS
.PP
Probably many.
.SH SEE ALSO
.PP
The SchoolMesh project is described at
<http://schoolmesh.mattiussilab.net/>.
.SH AUTHORS
Loris Tissino (loris.tissino\@mattiussilab.net).

