.TH SCHOOLMESH_POSIXACCOUNT_CHANGEFULLNAME 8 "August 6, 2009" "Schoolmesh User Manuals"
.SH NAME
.PP
schoolmesh_posixaccount_changefullname - Change full name for a
posix account of a user
.SH SYNOPSIS
.PP
schoolmesh_posixaccount_changefullname \f[I]username\f[]
\f[I]fullname\f[]
.SH DESCRIPTION
.PP
Use this script to change the full name (aka Gecos field) of a
posix account\.
.SH EXAMPLES
.PP
\f[CR]
      schoolmesh_posixaccount_changefullname\ john\ \"John\ Doe\"
\f[]
.SH BUGS
.PP
Probably many\.
.SH SEE ALSO
.PP
The SchoolMesh project is described at
<http://schoolmesh.mattiussilab.net/>\.
.SH AUTHOR
Loris Tissino (loris.tissino@mattiussilab.net)
