.TH SCHOOLMESH_POSIXFOLDER_PUTFILE 8 "January 2010" "Schoolmesh User Manuals"
.SH NAME
.PP
schoolmesh_posixfolder_putfile - Copy an uploaded file to a
user\[aq]s home (sub)directory
.SH SYNOPSIS
.PP
schoolmesh_posixfolder_putfile \f[I]username\f[] \f[I]tempname\f[]
\f[I]destinationpath\f[]
.SH DESCRIPTION
.PP
This script copies an uploaded file to a user\[aq]s directory\. The
user must exist\. The path is relative to user\[aq]s home
directory\.
.SH WARNINGS
.PP
The user who runs this (typically, www-data or apache) must be
allowed to run commands on behalf of other users (through sudo)\.
.SH EXAMPLES
.PP
\f[CR]
      schoolmesh_posixfolder_putfile\ john\.test\ /tmp\.Vm6STjrivF\ \[aq]/mydocs/My\ report\.odt\[aq]
\f[]
.SH BUGS
.PP
Probably many\.
.SH SEE ALSO
.PP
The SchoolMesh project is described at
<http://schoolmesh.mattiussilab.net/>\.
.SH AUTHOR
Loris Tissino (loris.tissino@mattiussilab.net)
