.TH SCHOOLMESH_POSIXACCOUNT_CREATEBASEFOLDER 8 "December 2011" "Schoolmesh User Manuals"
.SH NAME
.PP
schoolmesh_posixaccount_createbasefolder - Create the basefolder
for a user
.SH SYNOPSIS
.PP
schoolmesh_posixaccount_createbasefolder \f[I]username\f[]
.SH DESCRIPTION
.PP
Use this script to create the basefolder inside a user's directory.
The basefolder will have the name specified in
\f[I]schoolmesh.rc\f[] and will be the immutable flag.
.SH EXAMPLES
.PP
schoolmesh_posixaccount_createbasefolder john
.SH BUGS
.PP
Probably many.
.SH SEE ALSO
.PP
The SchoolMesh project is described at
<http://www.schoolmesh.mattiussilab.net/>.
.SH AUTHORS
Loris Tissino (loris.tissino\@gmail.com).

