.TH SCHOOLMESH_POSIXACCOUNT_CREATE 8 "October 2009" "Schoolmesh User Manuals"
.SH NAME
.PP
schoolmesh_posixaccount_create - Create a posix account for a user
.SH SYNOPSIS
.PP
schoolmesh_posixaccount_create \f[I]username\f[] \f[I]group\f[]
\f[I]fullname\f[]
.SH DESCRIPTION
.PP
Use this script to create a posix account\. Some checks are done
before the creation\.
.SH EXAMPLES
.PP
\f[CR]
      schoolmesh_posixaccount_create\ john\ students\ \[aq]John\ Doe\[aq]
\f[]
.SH BUGS
.PP
Probably many\.
.SH SEE ALSO
.PP
The SchoolMesh project is described at
<http://schoolmesh.mattiussilab.net/>\.
.SH AUTHOR
Loris Tissino (loris.tissino@mattiussilab.net)
