.TH SCHOOLMESH_UNOCONV_LAUNCH 8 "July 2010" "Schoolmesh User Manuals"
.SH NAME
.PP
schoolmesh_unoconv_launch - launch Unoconv and locks the screen at
once
.SH SYNOPSIS
.PP
schoolmesh_unoconv_launch
.SH DESCRIPTION
.PP
This script should be used by an unprivileged user just in order to
have a working instance of Unoconv converter running and listening
to client unoconv calls.
.PP
The user might have an automatic login, and therefore the script
locks the screen immediately after.
.PP
WARNINGS
.PP
This assumes that the user uses GNOME.
For other desktop environments, the command to lock the screen must
be found.
.SH BUGS
.PP
Probably many.
.SH SEE ALSO
.PP
The SchoolMesh project is described at
<http://schoolmesh.mattiussilab.net/>.
.SH AUTHORS
Loris Tissino (loris.tissino\@mattiussilab.net).

