.TH SCHOOLMESH_APPLICATION_UPDATE~ 8 "October 2009" "Schoolmesh User Manuals"
.SH NAME
.PP
schoolmesh_application_update~ - Update the application with the
newest SVN release
.SH SYNOPSIS
.PP
schoolmesh_application_update~ go
.SH DESCRIPTION
.PP
This script updates the application, making a backup of specific
configuraton files that might have been customized, and restoring
them afterwards.
.SH WARNINGS
.PP
This script does not backup the database.
It's better to run \f[I]schoolmesh_application_dumptables(8)\f[]
before its use.
.PP
The list of customizable files to backup might be incomplete.
.PP
Run at your own risk.
New versions may introduce regressions.
.SH EXAMPLES
.PP
\f[CR]
      schoolmesh_application_update~\ go\ \ 
\f[]
.SH BUGS
.PP
Probably many.
.SH SEE ALSO
.PP
The SchoolMesh project is described at
<http://schoolmesh.mattiussilab.net/>.
.SH AUTHORS
Loris Tissino (loris.tissino\@mattiussilab.net).

