.TH SCHOOLMESH 8 "September 29, 2009" "Schoolmesh utilities User Manuals"
.SH NAME
.PP
schoolmesh - command line utilities to be used with SchoolMesh web
application
.SH UTILITY LIST
.PP
schoolmesh_application_dumptables
.PP
schoolmesh_application_importtables
.PP
schoolmesh_application_update
.PP
schoolmesh_posixaccount_changefullname
.PP
schoolmesh_posixaccount_create
.SH DESCRIPTION
.PP
These utilities are really only basic wrapper scripts to be used
together with SchoolMesh\. The idea is to provide flexibility\. For
instance, instead of calling directly \f[B]useradd\f[], we call
\f[B]schoolmesh_posixaccount_create\f[]\. This way, if one day we
need to change the behaviour needed to add a system user (for
instance, using \f[I]ldap\f[], or contacting a different server),
we just need to change the wrapper scripts\.
.PP
Each utility should have its own man page (work in progress)\.
.SH BUGS
.PP
Probably many\.
.SH SEE ALSO
.PP
The SchoolMesh project is described at
<http://schoolmesh.mattiussilab.net/>\.
.SH AUTHOR
Loris Tissino
