.TH SCHOOLMESH_LOGINACCOUNT_SETPASSWORD 8 "December 2011" "Schoolmesh User Manuals"
.SH NAME
.PP
schoolmesh_loginaccount_setpassword - Change the login password for
a user
.SH SYNOPSIS
.PP
schoolmesh_loginaccount_setpassword \f[I]username\f[]
\f[I]password\f[]
.SH DESCRIPTION
.PP
This script changes the password of a user.
.SH EXAMPLES
.PP
schoolmesh_loginaccount_setpassword john 89jka76_23A
.SH BUGS
.PP
Probably many.
.SH SEE ALSO
.PP
The SchoolMesh project is described at
<http://schoolmesh.mattiussilab.net/>.
.SH AUTHORS
Loris Tissino (loris.tissino\@mattiussilab.net).

