.TH SCHOOLMESH_ODF_CONVERTER 8 "December 2011" "Schoolmesh User Manuals"
.SH NAME
.PP
schoolmesh_odf_converter - start, stop or show the status of
Unoconv Odf converter
.SH SYNOPSIS
.PP
schoolmesh_odf_converter start | stop | status
.SH DESCRIPTION
.PP
Use this script to start or stop Unoconv Odf converter.
.SH WARNINGS
.PP
This should be used by an unprivileged user with a minimal X
configuration and little privileges
.SH EXAMPLES
.PP
schoolmesh_odf_converter start schoolmesh_odf_converter stop
.SH BUGS
.PP
Probably many.
.SH SEE ALSO
.PP
The SchoolMesh project is described at
<http://schoolmesh.mattiussilab.net/>.
.SH AUTHORS
Loris Tissino (loris.tissino\@mattiussilab.net).

