generator:
  class: sfPropelGenerator
  param:
    model_class:           sfGuardUserProfile
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_user_profile
    with_propel_route:     1

    config:
      actions: ~
      fields:  ~
      list:
        display: [=Username,=FullName, Role]
        sort: [Role, asc]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
