dev:
  propel:
    param:
      classname: DebugPDO
test:
  propel:
    class: sfPropelDatabase
    param:
      classname: DebugPDO
      dsn: 'mysql:host=localhost;dbname=schoolmesh_test'
prod:
  propel:
    class: sfPropelDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=schoolmesh_prod'
all:
  propel:
    class: sfPropelDatabase
    param:
      dsn: 'mysql:dbname=schoolmesh;host=localhost'
      username: schoolmesh
      password: 2hzdBqtSc7MxM22u
      encoding: utf8
      persistent: true
      pooling: true
      classname: PropelPDO
