generator:
  class: sfPropelGenerator
  param:
    model_class:           WpitemType
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          wpitem_type
    with_propel_route:     1

    config:
      actions: ~
      fields:  ~
      list:
        display: [ title, description, state ]
        title: Workplan Item Types management
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
