default:
  credentials: [[ planning, schoolmaster, office ]]

list:
  credentials: [[ schoolmaster, office, backadmin ]]

viewwpevents:
  credential: [[ backadmin ]]

addwpevent:
  credential: [[ backadmin ]]

editwpevent:
  credential: [[ backadmin ]]

removewpevent:
  credential: [[ backadmin ]]
