default:
  credentials: [[ planning, schoolmaster, office ]]

list:
  credentials: [[ schoolmaster, office, backadmin ]]

viewwpevents:
  credentials: [[ backadmin ]]

addwpevent:
  credentials: [[ backadmin ]]

editwpevent:
  credentials: [[ backadmin ]]

removewpevent:
  credentials: [[ backadmin ]]
