default:
  credentials: [[ wpfr_submission ]]

list:
  credentials: [[ wp_adm_ok, wp_adm_no, fr_adm_ok, fr_adm_no, wp_sm_ok, wp_sm_no, fr_sm_ok, fr_sm_no, backadmin ]]

viewwfevents:
  credentials: [[ backadmin ]]

addwfevent:
  credentials: [[ backadmin ]]

editwfevent:
  credentials: [[ backadmin ]]

removewfevent:
  credentials: [[ backadmin ]]
