default:
  http_metas:
    content-type: text/html

  metas:
    title:        Progetto MattiussiLab
    #description:  symfony project
    #keywords:     symfony, project
    language:     it
    robots:        index, follow

  stylesheets:    [fluid]

#  javascripts:    [%SF_PROTOTYPE_WEB_DIR%/web/js/scriptaculous, %SF_PROTOTYPE_WEB_DIR%/web/js/prototype]

  has_layout:     on
  layout:         layout
