default:
  http_metas:
    content-type: text/html

  metas:
    title:        Progetto MattiussiLab
    #description:  symfony project
    #keywords:     symfony, project
    language:     it
    robots:        index, follow

  stylesheets:    [fluid]

  javascripts:    []

  has_layout:     on
  layout:         layout
