#!/bin/bash
# This script was automatically generated by SchoolMesh at <?php echo date('c') ?>

<?php $oldcontent=''; ?>
<?php foreach($checks as $check): ?>
<?php if($check->getContent()!=$oldcontent): ?>

# Commands concerning <?php echo $check->getContent() ."\n" ?>
<?php $oldcontent=$check->getContent() ?>
<?php endif ?>
<?php if ($check->getCommand()): ?>
 <?php echo $check->getCommand() . "\n" ?>
<?php endif ?>
<?php endforeach; ?>
