#!/bin/bash -x
# This script was automatically generated by SchoolMesh at <?php echo date('c') ?>

<?php foreach($userlist as $current_user): ?>
<?php if($current_user->getCountFailedChecks()>0): ?>

# Commands concerning <?php echo Generic::decode($current_user) ."\n" ?>
<?php foreach($current_user->getChecks() as $check): ?>
<?php if ($check->getCommand()): ?>
<?php echo Generic::decode($check->getCommand()) . "\n" ?>
<?php endif ?>
<?php endforeach ?>
<?php endif ?>
<?php endforeach ?>
