#!/bin/bash -x
# This script was automatically generated by SchoolMesh at <?php echo date('c') ?>

<?php foreach($checkList->getGroupNames() as $groupname): ?>
<?php if($checkList->getResultsByGroupName($groupname, Check::FAILED)+$checkList->getResultsByGroupName($groupname, Check::WARNING)>0): ?>

# <?php echo Generic::decode($groupname) ?>

<?php foreach($checkList->getChecksByGroupName($groupname) as $check): ?>
<?php if ($check->getCommand()!=''): ?>
<?php echo generic::decode($check->getCommand()) ?>
<?php endif ?>
<?php endforeach ?>
<?php endif ?>
<?php endforeach ?>
