generator:
  class: sfPropelGenerator
  param:
    model_class:           UserTeam
    theme:                 admin
    non_verbose_templates: false
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          user_team
    with_propel_route:     1

    config:
      actions: ~
      fields:  ~
      list:
        title: UserTeam
        display: [FirstName, LastName, Team, Role]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
